### ISSUE TITLE
Release the latest version in Marketplace

### ISSUE THREAD

**Issue by HelloRusk** [actions-ecosystem/action-regex-match#170]
## What you want to add

I would appreciate it if you could update the version of this workflow that resolves PR #165 

## Why this is needed

Because I am a heavy user of this project :)

**Comment by micnncim** [comment]
@HelloRusk Hi, I forgot to create a release :pray: Published [`v2.0.2`](https://github.com/actions-ecosystem/action-regex-match/releases/tag/v2.0.2) and overrode `v2` with `v2.0.2`.

**Comment by HelloRusk** [comment]
Thank you!
